// Package miviaauth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package miviaauth

import (
	"time"
)

// AcceptInvitationRequest defines model for AcceptInvitationRequest.
type AcceptInvitationRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// CreateInvitationResponseBody defines model for CreateInvitationResponseBody.
type CreateInvitationResponseBody struct {
	InvitationId   string `json:"invitation_id"`
	OrganizationId string `json:"organization_id"`
	Status         string `json:"status"`
}

// InvitationActionResponseBody defines model for InvitationActionResponseBody.
type InvitationActionResponseBody struct {
	Email          string `json:"email"`
	InvitationId   string `json:"invitation_id"`
	OrganizationId string `json:"organization_id"`
	Role           string `json:"role"`
	Status         string `json:"status"`
}

// InvitationRow defines model for InvitationRow.
type InvitationRow struct {
	CreatedAt          string `json:"created_at"`
	Email              string `json:"email"`
	ExpiresAt          string `json:"expires_at"`
	InvitationId       string `json:"invitation_id"`
	InvitedByAccountId string `json:"invited_by_account_id"`
	OrganizationId     string `json:"organization_id"`
	Role               string `json:"role"`
}

// InviteRequest defines model for InviteRequest.
type InviteRequest struct {
	Email string `json:"email"`
	Role  string `json:"role"`
}

// ListInvitationsResponseBody defines model for ListInvitationsResponseBody.
type ListInvitationsResponseBody struct {
	Invitations *[]InvitationRow `json:"invitations"`
}

// ListMembersResponseBody defines model for ListMembersResponseBody.
type ListMembersResponseBody struct {
	Members *[]MemberRow `json:"members"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponseBody defines model for LoginResponseBody.
type LoginResponseBody struct {
	Authenticated bool         `json:"authenticated"`
	Session       *SessionInfo `json:"session,omitempty"`
	User          UserInfo     `json:"user"`
}

// MemberActionBody defines model for MemberActionBody.
type MemberActionBody struct {
	AccountId      string `json:"account_id"`
	Email          string `json:"email"`
	OrganizationId string `json:"organization_id"`
	Role           string `json:"role"`
}

// MemberRow defines model for MemberRow.
type MemberRow struct {
	AccountId       string     `json:"account_id"`
	DisplayName     *string    `json:"display_name"`
	Email           string     `json:"email"`
	EmailVerifiedAt *time.Time `json:"email_verified_at,omitempty"`
	Lastname        *string    `json:"lastname"`
	Name            *string    `json:"name"`
	OrganizationId  string     `json:"organization_id"`
	Role            string     `json:"role"`
}

// OrganizationDeleteRequest defines model for OrganizationDeleteRequest.
type OrganizationDeleteRequest struct {
	ConfirmationKey string `json:"confirmation_key"`
}

// OrganizationPatchRequest defines model for OrganizationPatchRequest.
type OrganizationPatchRequest struct {
	DisplayName string `json:"display_name"`
}

// OrganizationProfileBody defines model for OrganizationProfileBody.
type OrganizationProfileBody struct {
	CreatedAt       time.Time `json:"created_at"`
	DisplayName     string    `json:"display_name"`
	OrganizationId  string    `json:"organization_id"`
	OrganizationKey string    `json:"organization_key"`
	UpdatedAt       time.Time `json:"updated_at"`
}

// PatchMemberRoleRequest defines model for PatchMemberRoleRequest.
type PatchMemberRoleRequest struct {
	Role string `json:"role"`
}

// PatchProfileResponseBody defines model for PatchProfileResponseBody.
type PatchProfileResponseBody struct {
	Authenticated bool     `json:"authenticated"`
	User          UserInfo `json:"user"`
}

// PreviewInvitationResponseBody defines model for PreviewInvitationResponseBody.
type PreviewInvitationResponseBody struct {
	AccountExists    bool      `json:"account_exists"`
	Email            string    `json:"email"`
	ExpiresAt        time.Time `json:"expires_at"`
	NeedsPassword    bool      `json:"needs_password"`
	OrganizationId   string    `json:"organization_id"`
	OrganizationKey  string    `json:"organization_key"`
	OrganizationName string    `json:"organization_name"`
	Role             string    `json:"role"`
}

// ProfileRequest defines model for ProfileRequest.
type ProfileRequest struct {
	DisplayName *string `json:"display_name,omitempty"`
	Lastname    *string `json:"lastname,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// RefreshResponseBody defines model for RefreshResponseBody.
type RefreshResponseBody struct {
	Authenticated bool        `json:"authenticated"`
	Session       SessionInfo `json:"session"`
	User          UserInfo    `json:"user"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email            string `json:"email"`
	OrganizationName string `json:"organization_name"`
	Password         string `json:"password"`
}

// RegisterResponseBody defines model for RegisterResponseBody.
type RegisterResponseBody struct {
	Status string `json:"status"`
}

// RegistrationStageBody defines model for RegistrationStageBody.
type RegistrationStageBody struct {
	Stage string `json:"stage"`
}

// RemoveMemberResponseBody defines model for RemoveMemberResponseBody.
type RemoveMemberResponseBody struct {
	AccountId      string `json:"account_id"`
	Email          string `json:"email"`
	OrganizationId string `json:"organization_id"`
	Role           string `json:"role"`
	Status         string `json:"status"`
}

// ResendInvitationResponseBody defines model for ResendInvitationResponseBody.
type ResendInvitationResponseBody struct {
	InvitationId   string `json:"invitation_id"`
	OrganizationId string `json:"organization_id"`
	Status         string `json:"status"`
}

// SessionExpiry defines model for SessionExpiry.
type SessionExpiry struct {
	ExpiresAt time.Time `json:"expires_at"`
}

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	Bearer    string    `json:"bearer"`
	ExpiresAt time.Time `json:"expires_at"`
}

// SessionResponseBody defines model for SessionResponseBody.
type SessionResponseBody struct {
	Authenticated bool          `json:"authenticated"`
	Session       SessionExpiry `json:"session"`
	User          UserInfo      `json:"user"`
}

// SystemAccessCheckResponseBody defines model for SystemAccessCheckResponseBody.
type SystemAccessCheckResponseBody struct {
	PlatformSuperAdmin bool `json:"platform_super_admin"`
}

// UserInfo defines model for UserInfo.
type UserInfo struct {
	AccountId            string  `json:"account_id"`
	DisplayName          *string `json:"display_name"`
	Email                string  `json:"email"`
	IsPlatformSuperAdmin bool    `json:"is_platform_super_admin"`
	Lastname             *string `json:"lastname"`
	Name                 *string `json:"name"`
	OrganizationId       string  `json:"organization_id"`
	OrganizationKey      string  `json:"organization_key"`
	OrganizationName     string  `json:"organization_name"`
	Role                 string  `json:"role"`
}

// VerifyRequest defines model for VerifyRequest.
type VerifyRequest struct {
	Token string `json:"token"`
}

// VerifyResponseBody defines model for VerifyResponseBody.
type VerifyResponseBody struct {
	Authenticated bool         `json:"authenticated"`
	Session       *SessionInfo `json:"session,omitempty"`
	Status        *string      `json:"status,omitempty"`
	User          *UserInfo    `json:"user,omitempty"`
}

// WireError defines model for WireError.
type WireError struct {
	Error WireErrorBody `json:"error"`
}

// WireErrorBody defines model for WireErrorBody.
type WireErrorBody struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// AuthLoginParams defines parameters for AuthLogin.
type AuthLoginParams struct {
	XMiviaAuthTransport *string `json:"X-Mivia-Auth-Transport,omitempty"`
}

// AuthAcceptInvitationParams defines parameters for AuthAcceptInvitation.
type AuthAcceptInvitationParams struct {
	XMiviaAuthTransport *string `json:"X-Mivia-Auth-Transport,omitempty"`
}

// AuthPreviewInvitationParams defines parameters for AuthPreviewInvitation.
type AuthPreviewInvitationParams struct {
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// AuthRefreshParams defines parameters for AuthRefresh.
type AuthRefreshParams struct {
	Authorization *string `json:"Authorization,omitempty"`
}

// AuthRevokeParams defines parameters for AuthRevoke.
type AuthRevokeParams struct {
	Authorization *string `json:"Authorization,omitempty"`
}

// AuthVerifyParams defines parameters for AuthVerify.
type AuthVerifyParams struct {
	XMiviaAuthTransport *string `json:"X-Mivia-Auth-Transport,omitempty"`
}

// AuthLoginJSONRequestBody defines body for AuthLogin for application/json ContentType.
type AuthLoginJSONRequestBody = LoginRequest

// AuthDeleteOrganizationJSONRequestBody defines body for AuthDeleteOrganization for application/json ContentType.
type AuthDeleteOrganizationJSONRequestBody = OrganizationDeleteRequest

// AuthPatchOrganizationJSONRequestBody defines body for AuthPatchOrganization for application/json ContentType.
type AuthPatchOrganizationJSONRequestBody = OrganizationPatchRequest

// AuthCreateInvitationJSONRequestBody defines body for AuthCreateInvitation for application/json ContentType.
type AuthCreateInvitationJSONRequestBody = InviteRequest

// AuthAcceptInvitationJSONRequestBody defines body for AuthAcceptInvitation for application/json ContentType.
type AuthAcceptInvitationJSONRequestBody = AcceptInvitationRequest

// AuthPatchMemberRoleJSONRequestBody defines body for AuthPatchMemberRole for application/json ContentType.
type AuthPatchMemberRoleJSONRequestBody = PatchMemberRoleRequest

// AuthPatchProfileJSONRequestBody defines body for AuthPatchProfile for application/json ContentType.
type AuthPatchProfileJSONRequestBody = ProfileRequest

// AuthRegisterJSONRequestBody defines body for AuthRegister for application/json ContentType.
type AuthRegisterJSONRequestBody = RegisterRequest

// AuthVerifyJSONRequestBody defines body for AuthVerify for application/json ContentType.
type AuthVerifyJSONRequestBody = VerifyRequest
