// Package agentkitdata holds embedded agent instructions data.
// The content is generated by gen_embed.go and baked into the binary.
package agentkitdata

import (
	"crypto/sha256"
	"fmt"
)

// AllFiles returns all embedded files as a map of repo-relative path → content.
func AllFiles() map[string]string {
	return _allFiles
}

// ReadFile returns the content of a file from the embedded store.
// Path is repo-relative (e.g., "AGENTS.md", ".ai/INDEX.md").
// Returns empty string if not found.
func ReadFile(path string) string {
	return _allFiles[path]
}

// HasFile checks if a path exists in the embedded store.
func HasFile(path string) bool {
	_, ok := _allFiles[path]
	return ok
}

// Version returns a sha256 content hash of all embedded files.
func Version() string { return _contentHash }

// _contentHash is computed at init.
var _contentHash string

func init() {
	h := sha256.New()
	// Sort keys for deterministic hash
	keys := make([]string, 0, len(_allFiles))
	for k := range _allFiles {
		keys = append(keys, k)
	}
	// Sort deterministically
	for i := 0; i < len(keys); i++ {
		for j := i + 1; j < len(keys); j++ {
			if keys[i] > keys[j] {
				keys[i], keys[j] = keys[j], keys[i]
			}
		}
	}
	for _, k := range keys {
		h.Write([]byte(k))
		h.Write([]byte{0})
		h.Write([]byte(_allFiles[k]))
		h.Write([]byte{0})
	}
	_contentHash = fmt.Sprintf("%x", h.Sum(nil))
}

// _allFiles is populated by the generated data.go file.
// This map MUST NOT be modified at runtime.
var _allFiles map[string]string

// RegisterFile is called by data.go init() to populate the file map.
func RegisterFile(path, content string) {
	if _allFiles == nil {
		_allFiles = make(map[string]string)
	}
	_allFiles[path] = content
}

// ReadAllFiles returns all files as a flat map for WriteInstructions.
func ReadAllFiles() (map[string][]byte, error) {
	result := make(map[string][]byte, len(_allFiles))
	for path, content := range _allFiles {
		result[path] = []byte(content)
	}
	return result, nil
}
