//go:build ignore

//go:generate go run gen_embed.go

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// gen_embed reads files from ship/ first, then .ai/ as fallback,
// and generates agentkitdata/data.go with init() calls to RegisterFile.
// Purpose: ship/ has GENERIC versions, .ai/ has HOST-SPECIFIC versions.
// We embed ship/ content into the binary; .ai/ stays on disk as host override.
func main() {
	outPath := filepath.Join("agentkitdata", "data.go")
	out, err := os.Create(outPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "cannot create %s: %v\n", outPath, err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprint(out, `// Code generated by gen_embed.go. DO NOT EDIT.

package agentkitdata

func init() {
`)

	// Walk ship/ directory for all generic shipped instructions
	filepath.Walk("ship", func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".md") {
			return nil
		}
		writeFileData(out, path)
		return nil
	})

	// Write from .ai/ for files NOT in ship/
	filepath.Walk(".ai", func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".md") {
			return nil
		}
		// Skip host-specific paths
		skipPrefixes := []string{".ai/plan", ".ai/plans", ".ai/policy", ".ai/quality", ".ai/handoffs", ".ai/templates", ".ai/phase", ".ai/events-", ".ai/agent-prompt", ".ai/invariants", ".ai/rules/30-go-standards", ".ai/rules/40-docs-ownership", ".ai/rules/80-commit-message", ".ai/rules/20-agent-quality", ".ai/skills/docs-update"}
		for _, skip := range skipPrefixes {
			if strings.HasPrefix(path, skip) {
				return nil
			}
		}
		// Check if ship/ has an override
		shipPath := strings.Replace(path, ".ai/", "ship/", 1)
		if _, err := os.Stat(shipPath); err == nil {
			return nil // ship/ version exists, skip
		}
		writeFileData(out, path)
		return nil
	})

	fmt.Fprint(out, "}\n")
}

func writeFileData(out *os.File, path string) {
	data, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "warning: cannot read %s: %v\n", path, err)
		return
	}
	// Escape special characters for Go string literals
	content := string(data)
	content = strings.ReplaceAll(content, "\\", "\\\\")
	content = strings.ReplaceAll(content, "\"", "\\\"")
	content = strings.ReplaceAll(content, "\n", "\\n")
	content = strings.ReplaceAll(content, "\r", "\\r")
	content = strings.ReplaceAll(content, "\t", "\\t")

	// Map path to what it should be on disk when auto-written
	diskPath := path
	if strings.HasPrefix(path, "ship/") {
		diskPath = strings.Replace(path, "ship/", ".ai/", 1)
		if diskPath == ".ai/AGENTS.md" {
			diskPath = "AGENTS.md" // AGENTS.md stays at repo root
		}
	}

	fmt.Fprintf(out, "\tRegisterFile(%q, \"%s\")\n", diskPath, content)
}
