package ledger

import (
	"fmt"
	"sync"
	"sync/atomic"
)

// DisplayNameGenerator allocates unique human-readable display names scoped to
// a run. Names use a base format like "agent-1", "agent-2", etc. and handle
// collisions with numeric suffixes.
type DisplayNameGenerator struct {
	mu      sync.Mutex
	counter atomic.Uint64
	used    map[string]bool
}

// NewDisplayNameGenerator creates a new generator with an empty used set.
func NewDisplayNameGenerator() *DisplayNameGenerator {
	return &DisplayNameGenerator{used: map[string]bool{}}
}

// Generate returns a unique display name for the given base name. If the base
// name is empty, it defaults to "agent". The generated name is guaranteed to
// be unique among all names generated by this instance.
func (g *DisplayNameGenerator) Generate(base string) string {
	if base == "" {
		base = "agent"
	}
	g.mu.Lock()
	defer g.mu.Unlock()
	n := g.counter.Add(1)
	name := fmt.Sprintf("%s-%d", base, n)
	for g.used[name] {
		n = g.counter.Add(1)
		name = fmt.Sprintf("%s-%d", base, n)
	}
	g.used[name] = true
	return name
}

// Reserve marks a display name as already used. Useful for deterministic test
// injection or restoring names from a persistent store.
func (g *DisplayNameGenerator) Reserve(name string) {
	g.mu.Lock()
	defer g.mu.Unlock()
	g.used[name] = true
}

// Reset clears all reserved names and resets the counter. Used in tests.
func (g *DisplayNameGenerator) Reset() {
	g.mu.Lock()
	defer g.mu.Unlock()
	g.used = map[string]bool{}
	g.counter.Store(0)
}
